### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Burmenska** [polywrap/polyfolio#126]
As a user I want to have https://polyfolio.vercel.app regularly updated from all branches automatically.

**Comment by Burmenska** [comment]
see discussion here https://discord.com/channels/796821176743362611/978604923371540491

**Comment by Brioline** [comment]
Closeb by: https://github.com/polywrap/polyfolio/pull/132/commits/811661dea0722c14b90349d160d4e31ba789c632
