### ISSUE TITLE
Dashboard: price fluctuations under the main title "Dashboard"

### ISSUE THREAD

**Issue by Burmenska** [polywrap/polyfolio#128]
Remove price fluctuations data from the page

**Comment by Niraj-Kamdar** [comment]
Can you add more description on this one?

**Comment by Brioline** [comment]
Hey @Niraj-Kamdar, I believe its this one

![Image](https://user-images.githubusercontent.com/33597141/169762034-6edb1d79-9a6a-4a9f-a280-d85c663b7920.png)

**Comment by RustamGass** [comment]
@Niraj-Kamdar Hello, I'll remove this data from AC, thank you!
