### ISSUE TITLE
Overview Component

### ISSUE THREAD

**Issue by DmitriyIvchenko** [polywrap/polyfolio#36]
Implement overview component 

![image](https://user-images.githubusercontent.com/34676102/155385469-05b0d26b-31ae-449c-ac92-4413669a75d7.png)

**DESIGN** https://www.figma.com/file/bAmE0FZ9jjYA9m4bLHadCb/Polyfolio?node-id=174%3A7489

Requirements
**Theming** support 
**Dynamic input parameters** support
**Localization** support
**Crossplatform** support

**Comment by Iangyl** [comment]
https://github.com/polywrap/polyfolio/commit/e2cd77ba6c4a647d6898c57fc7d05314ee56e99a
