### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by ramilexe** [polywrap/polyfolio#6]

**Comment by DmitriyIvchenko** [comment]
https://github.com/polywrap/polyfolio/commit/cbbd9463fd74d886265500c38b3f81bebc8e1f36

**Comment by DmitriyIvchenko** [comment]
https://github.com/polywrap/polyfolio/commit/0fc1615de5a82729f7c73623a4d9f5ef95812cd3

**Comment by DmitriyIvchenko** [comment]
https://github.com/polywrap/polyfolio/commit/afae6c796e652636b986b2164f0cbc1c333130eb
