### ISSUE TITLE
Mobile menu with data from sidebar

### ISSUE THREAD

**Issue by ramilexe** [polywrap/polyfolio#9]

**Comment by DmitriyIvchenko** [comment]
https://github.com/polywrap/polyfolio/commit/cbbd9463fd74d886265500c38b3f81bebc8e1f36

**Comment by DmitriyIvchenko** [comment]
https://github.com/polywrap/polyfolio/commit/82e28ea8dcf79df98963e0c55a31b0f74cf6c7b3
