### ISSUE TITLE
Add component for governance token on protocol page

### ISSUE THREAD

**Issue by cedricwaxwing** [polywrap/polyfolio#91]

**Comment by cedricwaxwing** [comment]
@Niraj-Kamdar can you provide more info for this please?

**Comment by Niraj-Kamdar** [comment]
Currently, we just have protocol vaults/LP tokens on the protocol page but it would be nice to also show the governance token balance of the same protocol that the user is hodling. 

Ex: On Aave protocol page, with protocol vault tokens aUSDC, aDAI, etc it would be nice to have a separate field on top for AAVE governance token with its price, balance and value

**Comment by cedricwaxwing** [comment]
@Niraj-Kamdar I've incorporated a similar pattern from the token page which provides an overview of the Governance Token values, including how much the particular user is holder:
https://www.figma.com/file/bAmE0FZ9jjYA9m4bLHadCb/Polyfolio?node-id=1235%3A33077

I'll hold off on closing this until you take a look. If it looks good, feel free to close. 👍

**Comment by Niraj-Kamdar** [comment]
LGTM!
